### ISSUE TITLE
could you release the code of real robot experiment?

### ISSUE THREAD

**Issue by Bailey-24** [vimalabs/VIMA#10]
Hi,
 you did a great job, if I want to use the algorithm with UR5 or fetch robot in the real world, how could I do it?

Thanks.

**Comment by yunfanjiang** [comment]
Hi @Bailey-24, thank you for your interest in our work. To clarify, this work was solely conducted in simulation. I would recommend to check [MOO](https://robot-moo.github.io/) since they compared against a "VIMA-like" baseline on real robots.
