### ISSUE TITLE
Can you release the Mask-RCNN model used for segmentation?

### ISSUE THREAD

**Issue by amitkparekh** [vimalabs/VIMA#13]
To directly reproduce and compare the results, can you release the mask rcnn model used for segmentation please? 

@yunfanjiang

**Comment by yunfanjiang** [comment]
hey @amitkparekh, thanks for the request. Yes it's possible and I'll let you know when it becomes alive. Meanwhile fine-tuning it should be relatively easy. We started with `mask_rcnn_R_50_FPN_3x` from [Detectron2](https://github.com/facebookresearch/detectron2). Please refer to Appendix C.4 in our paper for more details.
