### ISSUE TITLE
ModuleNotFoundError: No module named 'vima_bench'

### ISSUE THREAD

**Issue by YUHANG-Ma** [vimalabs/VIMA#14]
Hi, thanks for the stunning work! I am trying to running the demo however I got the error "ModuleNotFoundError: No module named 'vima_bench'". I'm guessing there may be some files you forgot to upload. Or could you tell me how to fix it? Thanks in advance!

**Comment by yunfanjiang** [comment]
Thanks for your interest in our project. Please follow the instruction [here](https://github.com/vimalabs/VimaBench#installation) to install `VIMABench`.
