### ISSUE TITLE
how to solve this import error?

### ISSUE THREAD

**Issue by torressliu** [vimalabs/VIMA#17]
![image](https://github.com/vimalabs/VIMA/assets/49422165/f500dce7-6360-404f-8133-98705fc69bd9)

**Comment by yunfanjiang** [comment]
Thanks for pointing this out. It is due to an accident commit and has been fixed in the [latest commit](https://github.com/vimalabs/VIMA/commit/3c2db0d35a75a73ace34e3103be97bd420f3b92e). Please update the codebase and try again.
