### ISSUE TITLE
Questions about prompt and Mask-RCNN

### ISSUE THREAD

**Issue by oxFFFF-Q** [vimalabs/VIMA#29]
Thank you for your previous response. I have a few more questions:

Regarding the prompt: For instance, given the example 'This is a dax {dragged_obj_1}. This is a zup {base_obj}. Put a dax into a zup.', I'm unclear on how the object names are associated with their respective segm or center positions. Could you explain this further?

Regarding Mask-RCNN: In another issue https://github.com/vimalabs/VIMA/issues/13, you provided the model's checkpoints and a link to Detectron2. Could you elaborate on how to load the RCNN model using those checkpoints? Once the pretrained model is loaded, can it directly generate segmentation from an input RGB image? Are there any specific parameters that I should be aware of or set when doing so?

Looking forward to your reply.

_Originally posted by @oxFFFF-Q in https://github.com/vimalabs/VIMA/issues/26#issuecomment-1689423600_

**Comment by yunfanjiang** [comment]
Thanks for the follow-up questions.

> I'm unclear on how the object names are associated with their respective segm or center positions. Could you explain this further?

Please note that object names were not used as part of model input. The names "dax" and "zup" are solely used in prompts of novel concept grounding tasks.

> Could you elaborate on how to load the RCNN model using those checkpoints? Once the pretrained model is loaded, can it directly generate segmentation from an input RGB image? Are there any specific parameters that I should be aware of or set when doing so?

It follows the interface provide by Detectron2. Specifically, assume `ckpt_path`, we can load it with
```
from detectron2.config import CfgNode, get_cfg
from detectron2.engine import DefaultPredictor


ckpt = torch_load(ckpt_path)
cfg = get_cfg()
ckpt_cfg = ckpt.pop("cfg")
cfg.update(**ckpt_cfg)
cfg.MODEL.WEIGHTS = ckpt_path

predictor = DefaultPredictor(cfg)
model = predictor.model
aug = predictor.aug
```

Assume input image `x`, the model can be queried after applying appropriate preprocessing.
```
img = aug.get_transform(x).apply_image(x)
```
