### ISSUE TITLE
How to render environment like in paper?

### ISSUE THREAD

**Issue by ezhang7423** [vimalabs/VIMA#3]
When I run the current evaluation the environment rendering looks a lot more basic than in the paper. How does one render the simulation environment with the proper lighting and textures?

**Comment by yunfanjiang** [comment]
Thank you for your interest in our work. As detailed in Appendix B in our paper, we applied [NVISII](https://github.com/owl-project/NVISII) raytracing renderer to enhance the visual quality for demonstration purpose. The real training renderer is more like the basic one.
