### ISSUE TITLE
About Success Rate calculating details

### ISSUE THREAD

**Issue by Deaddawn** [vimalabs/VIMA#31]
Hi there,
     I have already run the demo and through the paper carefully. I'm wondering is there a automatic way you guys calculate the success rate in your appendix results about the L1~L4 based on different methods(eg: Flamingo).Say, I gotta a one-time inference on the specific task(visual_manipulation) with the prompt(put obj1 into obj2), how do we know it succeeds in a **quantitative** way. And how to calculate this on a large test data with a automatic way?
      Thank you for your attention.

**Comment by Deaddawn** [comment]
Quote from the paper "Each task in
VIMA-B ENCH has a binary success criterion and does not
provide partial reward. During test time, we execute agent
policies in the simulator for multiple episodes to compute
a percentage success rate". Is there anyway you can explain this in a more detailed way?

**Comment by yunfanjiang** [comment]
This is achieved through the [method](https://github.com/vimalabs/VIMABench/blob/85b264703bd6eefd7f8ae20e99ebacd8a7e69e39/vima_bench/env/base.py#L675C10-L682) implemented in VIMABench. Concretely,

```
obs, _, done, info = env.step(...)

print(info)
>>> {"success": ..., "failure": ..., ...}
```

In practice, for each task we run multiple evaluations and compute an average success rate.
