### ISSUE TITLE
Some questions about the input observation

### ISSUE THREAD

**Issue by wxz1996** [vimalabs/VIMA#38]
Hi, I have a question, why do VIMA need both frontal and top-down views for the observation space，Can't just only give the top?

**Comment by yunfanjiang** [comment]
Hi there. For certain tasks only supplying top-down view might be suboptimal, such as `Follow Order` where one object is stacked on another. Additionally, due to legacy reason, we used to have tasks where frontal view is necessary to provide enough information for reasoning.
