### ISSUE TITLE
Problem with rendering

### ISSUE THREAD

**Issue by yeknafar** [vimalabs/VIMA#5]
Thanks for amazing project. 
When I run the demo, the output is a bit strange and the execution speed is not normal. There is a video of this show in the link below:
[link](https://drive.google.com/file/d/1bJ1Y4_WZJ9mZmtARenNdJPNmKMhAbIQn/view?usp=share_link)

Am I doing something wrong?

**Comment by yunfanjiang** [comment]
Hey, thanks for your interest in our work. The video looks normal to me. Please note that we use the default PyBullet renderer to produce the RGB frames for training data and interactive test environments. For demonstration purpose, we apply the [NVISII](https://github.com/owl-project/NVISII) raytracing renderer to enhance the visual quality.
