### ISSUE TITLE
Question about Dataset creation

### ISSUE THREAD

**Issue by zhanghuzhenyu** [vimalabs/VIMA#7]
Thank you so much for such an amazing job. 

Could you explain how you collected the dataset? I read on Hugging Face that "All demonstrations are generated by scripted oracles". But I don't really understand this process.

In addition to that I would like to ask, did every trajectory in the dataset successfully complete the task? I mean, they all end up with a reward of 1 instead of 0, right?

**Comment by yunfanjiang** [comment]
Hey, thank you for your interest in our work. To answer your questions, we use programmed bots to generate successful demonstrations. These bots are pre-programmed and have access to the ground-truth interpretation of task instructions. These scripts can be found [here](https://github.com/vimalabs/VIMABench/tree/main/scripts/oracle). Feel free to let me know if you have further questions.
